name: konekin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  carousel_slider: 4.2.1
  url_launcher: 6.2.1
  appinio_video_player: 1.2.2
  firebase_core: 2.24.0
  firebase_auth: 4.14.1
  cloud_firestore: 4.13.3
  firebase_storage: 11.5.3
  image_picker: 1.0.4
  youtube_player_flutter: 8.1.2
  dropdown_search: 5.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

